language: ruby
rvm:
  - 2.3.0
before_install:
  - gem update bundler
  - wget https://github.com/jgm/pandoc/releases/download/1.19.1/pandoc-1.19.1-1-amd64.deb -O pandoc.deb
  - sudo dpkg -i pandoc.deb
cache: bundler
